GET http://localhost:3001/

###
POST http://localhost:3001/api/coffeeShops
Content-Type: application/json

{
  "name": "Test",
  "website": "google.com",
  "description": "nice",
  "location": "wakanda"
}
###
GET http://localhost:3001/api/coffeeShops

###
PUT http://localhost:3001/api/coffeeShops/62fd421b8fa613cce3dd3111
Content-Type: application/json

{
  "name": "edited",
  "website": "google.com",
  "description": "nice",
  "location": "Kakaako"
}

