GET http://localhost:3001/

###
POST http://localhost:3001/api/coffeeShops
Content-Type: application/json

{
  "name": "Test",
  "website": "google.com",
  "description": "nice",
  "location": "wakanda"
}